### ISSUE TITLE
Effects thumbnail not loaded in cloudpluginview

### ISSUE THREAD

**Issue by dkmorb** [portalmod/mod-ui#28]
Change the path string, i'm able to load and see effect thumbnail. 
 File: cloudplugin.html
src="{{source}}effect/image/thumbnail.png?url={{urle}}"

Bye.

**Comment by brunogola** [comment]
hi, thanks for reporting. is this still an issue? looks ok for me

**Comment by dkmorb** [comment]
Hi Bruno,
after your update, all works correctly in that view.
